import Head from 'next/head'
import Godown from '../components/godown'

export default function Home() {
    return (
        <div className="flex min-h-screen justify-center items-center">
            <Head>
                <title>Godown</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Godown />
        </div>
    )
}
