import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hustle from '../components/hustle'

export default function Home() {
  return (
    <div className="flex min-h-screen justify-center items-center">
      <head>
        <title>Hustle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <Hustle />

    </div>
  )
}
