import Head from 'next/head'
import Leaderboard from '../components/leaderboard'

export default function Home() {
    return (
        <div className="flex min-h-screen justify-center items-center">
            <Head>
                <title>Leaderboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Leaderboard/>
        </div>
    )
}
