import Head from 'next/head'
import MakeAdeal from '../components/makeAdeal'

export default function Home() {
  return (
    <div className="flex min-h-screen justify-center items-center">
      <Head>
        <title>Make a deal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MakeAdeal />

    </div>
  )
}
