import Head from 'next/head'
import Mobile from '../components/mobile'
export default function Home() {
    return (
        <div className="flex min-h-screen justify-center items-center">
            <Head>
                <title>Mobile</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Mobile />
        </div>
    )
}
