import Head from 'next/head'
import Notes from '../components/notes'

export default function Home() {
    return (
        <div className="flex min-h-screen justify-center items-center">
            <Head>
                <title>Notes</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Notes/>
        </div>
    )
}
