import Head from 'next/head'
import Rules from '../components/rules'

export default function Home() {
  return (
    <div className="flex min-h-screen justify-center items-center">
      <Head>
        <title>Rules</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Rules />

    </div>
  )
}
